# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

# > # this means to ignore newlines until "baseurl:"
title: Sarah Binion | Designer & UI Developer
description: |
  Sarah Binion is a designer and ui developer from Chicago who believes good
  communication is good design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sarahbinion.com" # the base hostname & protocol for your site
twitter_username: srhbinion
github_username:  srhbinion
linked-in_username: sarahbinion
dribbble_username: sarahbinion
code-pen_username: srhbinion

# Build settings
markdown: kramdown
