[build]
  command = "npm run build"
  publish = "_src"

  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
