[build]
  publish = "_site"
  
  # Command to build your project
  command = "npm run build"
  
  # Optional: specify Node.js version (recommended for consistency)
  environment = { NODE_VERSION = "18" }

[build.environment]
  # Set any environment variables needed for the build
  # NODE_ENV = "production"
  # REACT_APP_API_URL = "https://api.example.com"

# Optional: Configure redirects
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200

# Optional: Configure headers
# [[headers]]
#   for = "/*"
#   [headers.values]
#     X-Frame-Options = "DENY"
#     X-XSS-Protection = "1; mode=block"