[build]
  command = "npm start"
  publish = "_src"

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
