[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "18"

# Optional: Configure redirects
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200

# Optional: Configure headers
# [[headers]]
#   for = "/*"
#   [headers.values]
#     X-Frame-Options = "DENY"
#     X-XSS-Protection = "1; mode=block"